name: Deploy to Fly.io
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.xxx }}
          password: ${{ secrets.xxx }}

      - name: Build and Push Docker image to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: ./aisuggestion
          file: ./aisuggestion/Dockerfile
          push: true
          tags: xxx/aisuggestion:latest
          platforms: linux/amd64

      - name: Deploy to Fly.io
        uses: superfly/flyctl-actions@1.3
        with:
          args: "deploy --image xxx/aisuggestion:latest -a aisuggestion"
        env:
          FLY_API_TOKEN: ${{ secrets.xxxtoken }}
